version: 2

updates:
  - package-ecosystem: npm
    directory: /uploader
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
